name: qr_scanner_workerbase
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  mobile_scanner: ^6.0.2
  drift: ^2.22.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.1
  share_plus: ^10.1.3
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  mockito: ^5.4.4
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/resources/img/user_ic.png
